### ISSUE TITLE
paging problem. [next] calculate wrong.

### ISSUE THREAD

**Issue by meadlai** [MartianZ/MartianZ-BLOG#1]
> > > import os
> > > os.getcwd()
> > > '/Volumes/dev/blog'
> > > post_dir = os.getcwd() + os.sep + 'posts'
> > > post_dir
> > > '/Volumes/mead/python/blog/posts'
> > > os.listdir(post_dir)
> > > ['.DS_Store', '2012-10-01-test1.markdown', '2012-10-03-test2.markdown', '2012-10-04-test3.markdown', '2012-10-05-test4.markdown']
> > > files = os.listdir(post_dir)
> > > len(files)
> > > 5

cos in the Mac OS X, there is a hidden file:
".DS_Store"

but in the debian linux server, it will paging wrong.

**Comment by MartianZ** [comment]
的确有这个问题，但是你的意思应该是，在OS X下会出现分页错误，在Linux Server下面是正常的吧？

**Comment by meadlai** [comment]
不是啊.Mac下面有个".DS_Store"隐藏文件, 但是linux上面没有隐藏,上面是debug的代码...呵呵
line#73行:我加了一个=等号,就okay了
if p + 4 <= len(file_list):

需要添加category 吗?blog分类一下?怎么样?

**Comment by MartianZ** [comment]
明白了，感谢pull request.

category的话我不是很需要这个功能呢…
